In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.8138487 , 0.26119585, 0.7404305 , 0.57179398],
       [0.38056378, 0.09832394, 0.95767212, 0.90101067],
       [0.70623705, 0.74428114, 0.32072036, 0.43429355],
       [0.33135283, 0.64570553, 0.1238874 , 0.7232967 ]])

In [3]:
randMat = mat(random.rand(4,4))

In [4]:
randMat.I

matrix([[ 2.48965752, -2.75922595,  1.1411914 ,  4.02693165],
        [-1.23638007,  1.51208307,  0.80041552, -2.79258577],
        [-3.69632866,  2.53177358, -0.84199375, -2.05083377],
        [ 2.73765075, -0.54523964, -0.87193517,  1.17858952]])

In [5]:
invRandMat = randMat.I

In [6]:
randMat*invRandMat

matrix([[ 1.00000000e+00,  5.55111512e-17,  5.55111512e-17,
         -2.22044605e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         -2.22044605e-16],
        [-2.22044605e-16,  4.51028104e-16,  1.00000000e+00,
         -5.55111512e-16],
        [-3.33066907e-16,  3.60822483e-16,  5.55111512e-17,
          1.00000000e+00]])